## Deliverable 2. Create a Customer Travel Destinations Map.

In [4]:
# Dependencies and Setup
import pandas as pd
import os
import requests
import gmaps

# Import API key
os.chdir("../")
from config2 import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [8]:
# 1. Import the WeatherPy_database.csv file. 
os.chdir("Weather_Database/")
city_data_df = pd.read_csv("WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
0,0,Sistranda,NO,63.73,8.83,275.32,85,100,6.12,moderate rain
1,1,Mataura,NZ,-46.19,168.86,283.97,91,100,1.41,overcast clouds
2,2,East London,ZA,-33.02,27.91,299.89,80,0,7.30,clear sky
3,3,Rikitea,PF,-23.12,-134.97,299.22,71,48,7.10,light rain
4,4,Atuona,PF,-9.80,-139.03,298.24,79,10,6.12,light rain

In [10]:
os.chdir("../")
os.chdir("Vacation_Search/")
os.getcwd()

'C:\\Users\\bkuro\\Documents\\MyCourses\\Toronto_BootCamp\\Unit 2 - Python\\World_Weather_Analysis\\Vacation_Search'

In [11]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature (°C) you would like for your trip? "))
min_temp = min_temp + 273.15
max_temp = float(input("What is the maximum temperature (°C) you would like for your trip? "))
max_temp = max_temp + 273.15

What is the minimum temperature (°C) you would like for your trip? 15
What is the maximum temperature (°C) you would like for your trip? 30

In [15]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) &
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.tail(50)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
592,592,Bosaso,SO,11.28,49.18,297.65,66,30,2.11,scattered clouds
593,593,Vredendal,ZA,-31.67,18.50,298.45,51,100,4.49,overcast clouds
595,595,Vilcun,CL,-38.65,-72.23,299.56,8,52,1.57,broken clouds
602,602,Moree,AU,-29.47,149.85,290.16,67,29,4.63,scattered clouds
606,606,Dera Ismail Khan,PK,31.83,70.90,288.48,35,0,1.76,clear sky
611,611,Quatre Cocos,MU,-20.21,57.76,300.21,81,61,3.63,light rain
612,612,Doctor Arroyo,MX,23.67,-100.18,288.58,52,27,0.90,scattered clouds
614,614,Alice Springs,AU,-23.70,133.88,290.90,68,0,0.00,clear sky
615,615,Santa Cruz De La Palma,ES,28.68,-17.76,293.23,68,75,6.17,broken clouds
621,621,Ende,ID,-8.84,121.66,297.78,88,100,0.51,overcast clouds
625,625,Puro,PH,12.48,123.38,297.54,87,100,5.21,overcast clouds
627,627,Colesberg,ZA,-30.72,25.10,302.94,23,26,2.61,scattered clouds
628,628,Maldonado,UY,-34.67,-54.92,291.81,94,100,6.72,overcast clouds
631,631,Funtua,NG,11.52,7.31,301.46,9,27,4.64,scattered clouds
633,633,Pilar,BR,-9.60,-35.96,302.11,51,57,6.90,broken clouds
637,637,Adrar,MR,20.50,-10.07,298.70,14,24,6.39,few clouds
638,638,Kimbe,PG,-5.55,150.14,296.84,94,100,1.19,overcast clouds
640,640,Faya,SA,18.39,42.45,289.21,75,28,1.40,scattered clouds
641,641,Cairns,AU,-16.92,145.77,299.12,84,43,2.57,scattered clouds
645,645,Cuamba,MZ,-14.80,36.54,294.15,96,100,0.71,moderate rain
647,647,Puerto Escondido,MX,15.85,-97.07,301.61,74,0,1.54,clear sky
648,648,Ormara,PK,25.21,64.64,294.97,54,0,5.98,clear sky
650,650,Miramar,US,25.99,-80.23,301.16,71,40,2.57,scattered clouds
651,651,Henties Bay,NaN,-22.12,14.28,296.96,79,14,3.64,light rain
653,653,Abancay,PE,-13.63,-72.88,289.73,85,100,1.31,overcast clouds
656,656,Honiara,SB,-9.43,159.95,297.75,88,100,0.45,overcast clouds
658,658,Camopi,GF,3.17,-52.32,299.05,92,85,1.98,overcast clouds
659,659,Pamanukan,ID,-6.28,107.81,298.71,85,100,2.01,overcast clouds
665,665,Copiapo,CL,-27.37,-70.33,294.98,32,0,5.22,clear sky
666,666,Kendari,ID,-3.94,122.50,297.47,93,99,1.73,overcast clouds
670,670,Biltine,TD,14.53,20.92,300.82,9,26,4.27,scattered clouds
671,671,Kenitra,MA,34.26,-6.58,293.55,63,12,4.39,few clouds
672,672,Rayagada,IN,19.17,83.42,291.31,71,47,0.78,scattered clouds
673,673,San Cristobal,VE,7.77,-72.22,297.25,39,96,3.70,overcast clouds
678,678,Rio Gallegos,AR,-51.62,-69.22,293.18,24,40,18.01,scattered clouds
680,680,Estacion Coahuila,MX,32.19,-115.00,297.02,18,0,3.42,clear sky
682,682,Dulce Nombre De Culmi,HN,15.10,-85.53,301.28,48,33,2.09,scattered clouds
683,683,Riyadh,SA,24.69,46.72,289.23,30,3,6.78,clear sky
684,684,Keetmanshoop,NaN,-26.58,18.13,301.66,54,90,3.09,overcast clouds
687,687,Sao Jose Da Coroa Grande,BR,-8.90,-35.15,302.95,62,52,6.61,broken clouds
689,689,General Teran,MX,25.27,-99.68,296.01,54,0,7.50,clear sky
690,690,Sijunjung,ID,-0.69,100.95,295.74,96,84,0.70,broken clouds
691,691,Florianopolis,BR,-27.61,-48.50,302.35,69,20,4.63,few clouds
692,692,Goure,NE,13.98,10.27,300.38,8,8,4.28,clear sky
693,693,San Andres,CO,12.58,-81.70,301.16,69,75,6.69,broken clouds
695,695,Mount Vernon,US,40.91,-73.84,288.18,46,75,8.75,broken clouds
696,696,Richards Bay,ZA,-28.78,32.04,297.99,78,0,5.14,clear sky
700,700,Sao Felix Do Xingu,BR,-6.64,-52.00,295.34,98,100,0.74,light rain
701,701,Friendswood,US,29.53,-95.20,291.50,85,75,3.60,haze
702,702,Praia Da Vitoria,PT,38.73,-27.07,291.29,68,20,5.26,few clouds

In [13]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                312
City                   312
Country                304
Lat                    312
Lng                    312
Max Temp               312
Humidity               312
Cloudiness             312
Wind Speed             312
Weather Description    312
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
#  Rows are filled.  8 country symbols are left out but makes "no" effect on the data.

In [18]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df.insert(0,"Hotel Name","")
# 5b. Create a new column "Hotel Name"
hotel_df.head(10)

   Hotel Name         City Country  Max Temp    Lat     Lng
2              East London      ZA    299.89 -33.02   27.91
3                  Rikitea      PF    299.22 -23.12 -134.97
4                   Atuona      PF    298.24  -9.80 -139.03
5                    Kapaa      US    293.14  22.08 -159.32
8                 Pochutla      MX    302.05  15.74  -96.47
11                Hermanus      ZA    296.43 -34.42   19.23
12                 Le Port      RE    300.15 -20.94   55.29
14                  Castro      BR    298.84 -24.79  -50.01
15              Butaritari      KI    300.85   3.07  172.79
17                 Kavieng      PG    300.27  -2.57  150.80

In [77]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key,
    "location": ""
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]   
    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.

    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        # Clean the hotel names:
        split_string = hotel_df.loc[index, "Hotel Name"].split(",",1)
        split_string = split_string[0].split("(",1)
        split_string = split_string[0].split("-",1)
        hotel_df.loc[index, "Hotel Name"] = split_string[0]
        
        print(hotel_df.loc[index, "Hotel Name"])
    except:
        print("Hotel not found... skipping.")
    # I'm conflicted so... change Kelvin to Celcius!!!
    hotel_df.loc[index, "Max Temp"] = hotel_df.loc[index, "Max Temp"] - 273.15

Tu Casa
People ThankYou
Villa Enata
Sheraton Kauai Coconut Beach Resort
Hotel Posada San Jose
Misty Waves Boutique Hotel
KORBEY D'OR OUEST
CHACARA BAILLY
Isles Sunset Lodge
Nusa Island Retreat
Pension Oaoa
The Regency Hotel
Paraiso Escondido
Hotel do Campo
LE PAPYRUS
Shandrani Beachcomber Resort & Spa
Bils' Villa
Casona Del Muelle
Nuevo Hotel Plaza
Hostal Las Lilas
Desert Gardens Hotel
Pousada Porto Praia
Maui Seaside Hotel
Scoop Guest House
Hotel San Isidro Oficial
Takalvan Motel
Hôtel Le Dronmi
Gran Hotel Mar del Plata
El rranchito michuacan de ocampos
Beachfront Voyager Motor Inn
Bredasdorp Country Manor
Quinta da Meia Eira
DoubleFAG
Holiday Inn Express Lompoc
Ha'apai Beach Resort
The Halyards Hotel
Welcomhotel By ITC Hotels
Finch Bay Galapagos Hotel
Paradise Inn
Hilo Hawaiian Hotel
Pousada dos Navegantes
RELAHARA
Quality Suites Vila Velha
LÜDERITZ NEST HOTEL
Taloa Heights
Sandpiper Motel
Seagulls Inn Namatani
Abaco Beach Resort
Sa Mansion By Yoho
Lidera
Hotel Hain
Chelpasin
Hotel Citra
Chambres d'hôte "La Trinité"
The Esplanade Hotel
Oyster Bay House Rental
ibis Styles Mt Isa Verona
VS Villa
Motel 6 Sinton
Hotel Star inn Peniche
Hotel Aguiar
Hotel Chik Chik Namibe
Bora
Mini Hotel Central
Southern Sun Cape Sun
Hotel Restaurant Turístico Casablanca
Majestic Oasis Apartments
Gite de la RYAWA
39 On Nile Guest House
HUALUXE Yangjiang City Center
Broadwater Mariner Resort
Guest House HESADA
HS Hotsson Smart Acapulco
Lorengau Harbourside Hotel
Cititel Penang
Daydream Motel & Cottages
Lakatoro Palm Lodge
HAMDAN PLAZA HOTEL SALALAH
Euskadi Hotel
Hôtel Panorama
Moon light Furnished Units
Uncle Junior Robert
Holiday Inn Express & Suites Elk Grove Central
Goba Lodge
Grage Hotel Bengkulu
Poutur Pousada
Timotel Hotel
Casa Das Faias
Parkhurst B&B
Phú Quý
Derogongan Residence
Hotel Residencial Centro
Posada del Inti Centro
Hotel Xaguate
Parador de Ayamonte
Country Lodge
Lovers Point Inn
Tanna Lodge
Villa Mar Colina
Atlantis Hotel
Hotels in Lakshadweep Islands
Blue Bay Lodge
Ahipara Holiday Park
Mary River Motor Inn
La Quinta Inn & Suites by Wyndham Atlanta Roswell
OlusHome
Beira Terrace Hotel
Shishime Hotel
Hotel Victoria
Dillon Express Inn
The Second Room
Bonifacio Lodge
Hospitality Carnarvon
Hotel Olako
Keleti Beach Resort
Karina Guest House
Osprey Beach Hotel
Halane Hotel and Restaurent
The Commodore
SEGAYA PROPERTY
حامد محمد نور
Quinta Samay
Pousada do Eti
Millennia Estate
Shellharbour Resort & Conference Centre
Hotel Kununurra
Bushido Lodge
4 On Housman Backpackers
Kost Pria
Gula Jan Abdulai
Thanda Vista B&B
Lazy River Motor Inn
hotêl doufoulougou
Maltahöhe Hotel
Walton Cottage
Axim Beach Resort And Spa
Casa Tia Villa
Hotel Arena Gruesa
Hotel Boutique Las Azucenas
Ghazi Guest House
Marriott's Ko Olina Beach Club
Hotel Tesoro Los Cabos
Holiday Inn Express & Suites Pensacola W I
Hotel Porto Santo & Spa
Hôtel les Oliviers Marovoay
Oyster Box Guesthouse
Dibbo areaمنطقة دبو
Melrose
Codrington Gardens Bed And Breakfast
Pine Tree Motel
ZINGARA 76ft Catamaran
Hotel Miramar
Auki Motel
Pousada Porto De Canoas
Bay Retreat Motel
Dhukurrdji Lodge
La Case Bambou
The Irish Village
Kilakarai Home Stays
Tiger Tower Hotel
LT Aparthotel
Undulata Country Lodge
Swetha lodge
Mystic Sands Beachfront Accommodation
محطة ام الارانب
Daru Lodge
Shruti nilanga rice and vada pav and tea centre
Palolem Beach Resort
Baymont by Wyndham Lazaro Cardenas
Casa Maquia
Laurel Inn & Conference Center
Hotel Mirage
Apollon Motor Inn
Dhidhoo beach
Macs
Hotel Ultramar
Port Lincoln Hotel
Hotel Anfora
Hotel Santika Palu
Liceo Bolivariano 19 De Abril
janelas do mar
Le Gîte d’Iracoubo
Hostel Luxury A/C
Don Eddie's Landing
Haajy Guest House 1
Pestana Bahia Praia
Howard Johnson by Wyndham Ocala FL
Pereybere Hotel & Spa
900 Boutique INN
Mercure Padang
Pousada 2 Irmãos
Hosteria Sampedro
COMBUESA
Screensaver
FLAT RIO DE JANEIRO
Bungalow 63
RANCHO SANTA ELENA
OYO 3271 Homestay Pandian
Posada Paraiso
Hotel Maxim's
Hotel Arrarte
Center Hotel Punta Alta
Monty Brooms Guest House
Saville Free Shop
Sing and Swing Lodge
Hospitality Esperance
Nam Long Hotel
Casa Laguna
Hotel Kou
Valle Aridane
Nathagar Pallivasal
Yuehai Hotel
Hotel Praia Morena
Uruna Bay Retreat
Hotel San Juan
Club El Pelícano
Leonardo Family Beach House 1
Ludlow Farmstay
Lords Inn Porbandar
Aryaduta Hotel
Hotel Abad
Diego De Almagro Coyhaique
"Plantation Bed and Breakfast
Veranda Paul et Virginie Hotel & Spa
Chelelwa Charlets
Hotel Castelo
Hampton Inn Channel Islands Harbor
Apt downtown Waltham
Holiday Inn Express Richmond
Hospedaje Familiar
Golden Berries Hotel and Convention
Foyer ADM
Hot Springs Resort
Hôtel & Restaurant DIANA Ambilobe
Direct Hotels
Senthil Residency
penginapan citra alam
Raybow International Hotel
Rancho das Pedras Hotel
Dena Hotel
Swiss
Storyboard Beach Resort
Fengshui Residence
Welcombe Hotel
Sur Plaza Hotel
Butterfly Beach Hotel
Red Sea Hotel
Tharrakamma Guest House
Rayen
Molika Springs Motel
Haji Ayub Residence
Sunrise Attitude Hotel
Hotel Plaza
Desert Palms Alice Springs
H10 Taburiente Playa
Dwi Putra Hotel
Bhelekazi Guesthouse
La Cimarrona
Elbintu Restaurant And Motel
Pousada e churrascaria Manguaba
Kimbe Bay Hotel
أبو تركي للوحدات السكنيه
Mantra Trilogy Cairns
Hotel Vision
Aldea del Bazar Hotel and Spa
Crystal Beach and Camping Resort Ormara
Chef Jassy
Fishermans Guest House
Siball Hotel
Heritage Park Hotel
La pousada
Paris Day Hotel Pamanukan
San Francisco de La Selva
Hotel Wixel
Hôtel Trois Étoiles de Biltine
Bienvenue chez vous
Hotel Swagath
Pirineos
Hotel Santa Cruz
carroceria y pintura Kikones
Hotel Zuniama
InterContinental Riyadh
Quiver Inn Guesthouse
Crôa Mares Hotel
OYO Hotel Garate
Hotel Bukik Gadang
Hotel Boutique Quinta das Videiras
Hotel Arena Blanca
Studio
BON Hotel Waterfront Richards Bay
Rio Xingu Camping
Oakhollow RV Park
Hotel Branco I

In [78]:
# 7. Drop the rows where there is no Hotel Name.  Formerly 312, now 293.
hotel_df = hotel_df[hotel_df["Hotel Name"] != '']
hotel_df.count()

Hotel Name    293
City          293
Country       286
Max Temp      293
Lat           293
Lng           293
dtype: int64

In [79]:
# 8a. Create the output File (CSV)
output_data_file = "HotelCities.csv"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [80]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} K</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [81]:
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
# 11b. Display the figure
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))